export const GOODS_REDUCER_NAME = 'ProductsList';
export const CURRENT_ITEM_REDUCER_NAME = 'CurrentItem';

export const GET_ITEMS = 'GET_ITEMS';
export const GET_ITEMS_FETCHING_START = 'GET_ITEMS_FETCHING_START';
export const GET_ITEMS_FETCHING_SUCCEEDED = 'GET_ITEMS_FETCHING_SUCCEEDED';
export const GET_ITEMS_FETCHING_FAILED = 'GET_ITEMS_FETCHING_FAILED';

export const GET_ITEM = 'GET_ITEM';
export const GET_ITEM_FETCHING_START = 'GET_ITEM_FETCHING_START';
export const GET_ITEM_FETCHING_SUCCEEDED = 'GET_ITEM_FETCHING_SUCCEEDED';
export const GET_ITEM_FETCHING_FAILED = 'GET_ITEM_FETCHING_FAILED';
